name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate WordPress MCP
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Validate Project Structure
      run: |
        echo "================================"
        echo "WordPress MCP Validation"
        echo "================================"
        echo
        
        # Check essential files exist
        echo "Checking core files..."
        [ -f "manifest.json" ] && echo "✅ manifest.json" || exit 1
        [ -f "README.md" ] && echo "✅ README.md" || exit 1
        [ -f "LICENSE" ] && echo "✅ LICENSE" || exit 1
        [ -d "mcp-server" ] && echo "✅ mcp-server/" || exit 1
        [ -d "wp-mcp-plugin" ] && echo "✅ wp-mcp-plugin/" || exit 1
        
        echo
        echo "Checking MCP server files..."
        [ -f "mcp-server/server.py" ] && echo "✅ server.py" || exit 1
        [ -f "mcp-server/wp_client.py" ] && echo "✅ wp_client.py" || exit 1
        [ -f "mcp-server/requirements.txt" ] && echo "✅ requirements.txt" || exit 1
        
        echo
        echo "Checking WordPress plugin..."
        [ -f "wp-mcp-plugin/wp-mcp-plugin.php" ] && echo "✅ wp-mcp-plugin.php" || exit 1
        
        echo
        echo "================================"
        echo "✅ All validations passed!"
        echo "================================"
    
    - name: Validate manifest.json
      run: |
        python3 -c "
        import json
        try:
            with open('manifest.json', 'r') as f:
                data = json.load(f)
            print('✅ manifest.json is valid JSON')
        except Exception as e:
            print(f'❌ Invalid manifest.json: {e}')
            exit(1)
        "

  syntax-check:
    name: Python Syntax Validation
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Check Python Syntax
      run: |
        echo "================================"
        echo "Python Syntax Validation"
        echo "================================"
        echo
        
        # Find and compile all Python files, excluding virtual environments
        # Using the approach recommended by Gemini for robustness
        echo "Checking Python files in mcp-server/..."
        
        # Count files for summary
        file_count=$(find mcp-server/ -path '*/venv/*' -prune -o -path '*/.venv/*' -prune -o -path '*/__pycache__/*' -prune -o -name "*.py" -type f -print | wc -l)
        echo "Found $file_count Python files to check"
        echo
        
        # List files being checked for transparency
        find mcp-server/ -path '*/venv/*' -prune -o -path '*/.venv/*' -prune -o -path '*/__pycache__/*' -prune -o -name "*.py" -type f -print | while read file; do
          echo "  Checking: $file"
        done
        echo
        
        # Perform actual syntax validation
        find mcp-server/ -path '*/venv/*' -prune -o -path '*/.venv/*' -prune -o -path '*/__pycache__/*' -prune -o -name "*.py" -type f -exec python -m py_compile {} +
        
        if [ $? -eq 0 ]; then
          echo "================================"
          echo "✅ All Python files have valid syntax!"
          echo "================================"
        else
          echo "================================"
          echo "❌ Syntax errors found!"
          echo "================================"
          exit 1
        fi
